<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPU9CjYT\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPU9CjYT/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPU9CjYT.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPU9CjYT\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPU9CjYT\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'PU9CjYT',
    'container.build_id' => '74864841',
    'container.build_time' => 1538236318,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPU9CjYT');
